# Generated by Django 5.1.1 on 2024-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_jobseeker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
