# Generated by Django 5.1 on 2024-08-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('freelance', 'Freelance')], max_length=50)),
                ('applicants_needed', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('job_description', models.TextField()),
                ('job_category', models.CharField(max_length=100)),
                ('job_site', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('experience_level', models.CharField(choices=[('expert', 'Expert'), ('senior', 'Senior'), ('intermediate', 'Intermediate'), ('junior', 'Junior'), ('entry', 'Entry')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employer')),
            ],
        ),
    ]
