# Generated by Django 5.1 on 2024-08-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_alter_user_managers_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authentication.user'),
        ),
    ]
