# Generated by Django 5.1.1 on 2024-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_required_skills_delete_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants_needed',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10),
        ),
    ]
